### ISSUE TITLE
seed command failed on empty main configuration

### ISSUE THREAD

**Issue by shyaminayesh** [avanciro/pebble#1]
Seed command failed to execute if the seed configuration section is not present in the main configuration file ```pebble.yml```.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7f8aa7]

goroutine 1 [running]:
github.com/spf13/viper.(*Viper).find(0x0, 0x918cca, 0x3, 0x3, 0xc0000a60b0)
        /home/shyamin/Partitions/data/Developments/go/pkg/mod/github.com/spf13/viper@v1.4.0/viper.go:979 +0x37
github.com/spf13/viper.(*Viper).Get(0x0, 0x918cca, 0x3, 0x36, 0xc000138000)
        /home/shyamin/Partitions/data/Developments/go/pkg/mod/github.com/spf13/viper@v1.4.0/viper.go:671 +0x7c
pebble/cmd/seed.seed(0xce99c0, 0xd1cda0, 0x0, 0x0)
        /home/shyamin/.cache/yay/pebble/src/pebble-1.0.1-beta/cmd/seed/seed.go:47 +0x3ab
github.com/spf13/cobra.(*Command).execute(0xce99c0, 0xd1cda0, 0x0, 0x0, 0xce99c0, 0xd1cda0)
        /home/shyamin/Partitions/data/Developments/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0xce8ca0, 0xc000123f50, 0x1, 0x1)
        /home/shyamin/Partitions/data/Developments/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
        /home/shyamin/Partitions/data/Developments/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
pebble/cmd.Dispatch()
        /home/shyamin/.cache/yay/pebble/src/pebble-1.0.1-beta/cmd/app.go:32 +0x176
main.main()
        /home/shyamin/.cache/yay/pebble/src/pebble-1.0.1-beta/pebble.go:8 +0x20
```

**Comment by shyaminayesh** [comment]
remove seed command temporary to focus on migration part.
